### ISSUE TITLE
Error using InlinePolicy for SSO PermissionSet

### ISSUE THREAD

**Issue by srawln** [awslabs/aws-cloudformation-iam-policy-validator#11]
Hello,

Thanks for creating this tool!  I'm trying to use it to validate AWS Single Sign-On (SSO) inline policies. I see that SSO policies are supported, and for ManagedPolicies it's working great, but I'm getting an error `ERROR:  <policy statement> is not of type 'object'` for InlinePolicy statements.

Here is a minimal example of an SSO Resource with an inline policy:

```
Resources:  
  ExampleSSOPermSet:
    Type: AWS::SSO::PermissionSet
    Properties: 
      Name: MyExample
      Description: Example inline SSO policy 
      InstanceArn: 'arn:aws:sso:::instance/ssoins-1111111111111111'
      InlinePolicy: '{
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "ec2::Describe*",
              "ec2::List*"
            ],
            "Resource": "*"
          }
        ]}'
```

Example running cfn-policy-validator with logging:
```
cfn-policy-validator validate --template-path ./example.yaml --region ca-central-1 --enable-logging
2022-01-18 16:45:38,766 - cfn-policy-validator - INFO - Validating template ./example.yaml
2022-01-18 16:45:39,372 - cfn-policy-validator - INFO - Parsing resource type AWS::SSO::PermissionSet with logical name ExampleSSOPermSet..
ERROR: '{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "ec2::Describe*", "ec2::List*" ], "Resource": "*" } ]}' is not of type 'object', Path: ExampleSSOPermSet.Properties.InlinePolicy
```

Is this type of SSO inline policy supported?  If not, what is needed to support this?  Any workarounds?  Or is there something I'm doing wrong?

Thanks for any assistance you can provide!

Steve

**Comment by mluttrell** [comment]
Thank you for taking the time to try out the tool! 

Can you give the following policy a try?

```
Resources:  
  ExampleSSOPermSet:
    Type: AWS::SSO::PermissionSet
    Properties: 
      Name: MyExample
      Description: Example inline SSO policy 
      InstanceArn: arn:aws:sso:::instance/ssoins-1111111111111
      InlinePolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:Describe*
              - ec2:List*
            Resource: "*"
```

The validator is expecting a JSON object (as opposed to a string) for the InlinePolicy property given the CloudFormation spec for SSO::PermissionSet here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html
