### ISSUE TITLE
Conditional path "StringLike"  is throwing error after 0.0.28 release

### ISSUE THREAD

**Issue by ariasvzla** [awslabs/aws-cloudformation-iam-policy-validator#33]
Hi there,

The validator is throwing ERROR like the following:
ERROR: {'StringLike': {'iam:AWSServiceName': 'lakeformation.amazonaws.com'}} is not of type 'string', Path: Condition

for conditional block in yaml: 
```
Condition:
                  StringLike:
                    iam:AWSServiceName: lakeformation.amazonaws.com
```

I tried to quote it but did not pass validation.

The following did not pass validation either:

```
Condition:
                  StringLike:
                    "iam:AWSServiceName": lakeformation.amazonaws.com
```
```
Condition:
                  StringLike:
                    "iam:AWSServiceName": "lakeformation.amazonaws.com"
```
I downgrade to version 0.0.27 and validation against the original block passed.

**Comment by mluttrell** [comment]
Thanks for reporting this.  I think I have an idea of what's causing it.  

Can you share the rest of the resource that's causing the error?

**Comment by mluttrell** [comment]
I just pushed v0.0.29 that should fix your issue.  Please let me know if it does, when you get a chance.

**Comment by ariasvzla** [comment]
Hi Matt, I did a test and it works as expected, thank you for the fix.
