### ISSUE TITLE
Support for AWS::URLSuffix intrinsic function

### ISSUE THREAD

**Issue by patlougheed** [awslabs/aws-cloudformation-iam-policy-validator#8]
Running against a CDK-generated CF template is generating the following error:

`ERROR: Unable to find a referenced resource or parameter in template: AWS::URLSuffix`

[A stripped down template that errors out is attached.](https://github.com/awslabs/aws-cloudformation-iam-policy-validator/files/7445398/test.json.txt)

Tested against 0.0.6 installed via pip on 2021-10-29.

**Comment by mluttrell** [comment]
Thanks for the request!  I agree that URLSuffix should be supported and will add it to the backlog.
